{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nginx.serviceAccountName" . }} # Or use a static name string
  namespace: {{ .Release.Namespace | default "default" }}
{{- end }}
