---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: argocd
spec:
  encryptedData:
    password: AgBXGRThYILXjhCneI8pZXLq2+Elp20fhieF5R6n6ATPQBlDRRZVykxRIb7D6oQDrcA3EFBh1zHL9wziTkzuz69cVRlo6MmICF/rXSmwR1BN3cXApeuEa7GfkhYFqCZ8mzFxzyNmIBP/GWle1kYbnj6h9O8jlsnJOs3Ec/zMDHHZX5EUZ73q2IAYmxhPNK/isBGh4Lmz3GtKTrFlW+VCxJeRmyaH6ndeYwmtxVmBCYzVOYRthd9ylP+v8Npf8V4mEL4uqSMa37mE0xgu6z5SFxaXLhRcAUHwR0IKKISpYro1f3ALz98G+rTxfBzEWJl1RL6ktAc+SEsn5w7u0JId5WNkT6BpQJpOM5P7Y0tvMHN4swbxWZ47ZJV2/B9XxqDOnPnz60zIJz8vYqoK4w8eNtOPv/FELdK92s18vIbJdG5maQQXcOqFsh6IvIsN83KbJ8kvc2e0IXnGnpLxs+86OK21ZL4s1kd7QJ3x7a0iv3c8cp2G9M3oGk/Xh5nv5Ao/YyjezhT1QwO1fJe8uFpP23bD7l0KVI9x/2pwcfXpekVMdfWlYc7zksuEHuF9+aOb3tw9vRQZp1AfbJUDZWPSpDKyYJ9Djh+W0ioh/PEWtEXvxi5LENH+VR76QyeCkvYGcfv4AaoA/IK1WuWhXEmPCqQyPfyJhsLj0YQFHp8Efln8tM++hb2UbjRk+nbMdqJoBBdVcrnUuTURQueurw==
  template:
    metadata:
      name: db-secret
      namespace: sealed-secrets
    type: Opaque
