apiVersion:  argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://falcosecurity.github.io/charts'
    chart: falco
    targetRevision: 4.21.2
    helm:
      values: |
        driver:
          kind:  modern_ebpf
        falcosidekick:
          enabled: true
          webui:
            enabled: true
        jsonOutput: true
        log_stderr: true
        log_syslog: false
        output_timeout: 2000
        stdout_output:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true 