apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Mihirbhandari08/gitops-base.git
      targetRevision: HEAD
      path: nginx
      helm:
        valueFiles:
          - $values/environments/prod/values.yml
    - repoURL: https://github.com/Mihirbhandari08/gitops-base.git
      targetRevision: HEAD
      ref: values        
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
