cleanupController:
  enabled: true
  image:
    registry: ghcr.io
    repository: kyverno/cleanup-controller
    # Leave tag empty or omit it entirely to automatically match your Helm chart's appVersion
    tag: "" 

upgradeJob:
  enabled: false
