name: CI - Manifest Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install yamllint
        run: pip install yamllint
      
      - name: Run YAML Linter
        run: yamllint .

      - name: Validate Kubernetes Manifests
        uses: yannh/kubeconform-action@v0.0.8
        with:
          validate_all: true
          directory: nginx/
